"""empty message

Revision ID: 28e0f646b931
Revises: None
Create Date: 2015-03-11 13:44:29.260846

"""

# revision identifiers, used by Alembic.
revision = '28e0f646b931'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('username', sa.String(length=80), nullable=True))
    op.drop_index('ix_myprofile_email', table_name='myprofile')
    op.drop_constraint(u'myprofile_nickname_key', 'myprofile', type_='unique')
    op.create_unique_constraint(None, 'myprofile', ['username'])
    op.drop_column('myprofile', 'nickname')
    op.drop_column('myprofile', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myprofile', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('myprofile', sa.Column('nickname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'myprofile', type_='unique')
    op.create_unique_constraint(u'myprofile_nickname_key', 'myprofile', ['nickname'])
    op.create_index('ix_myprofile_email', 'myprofile', ['email'], unique=True)
    op.drop_column('myprofile', 'username')
    ### end Alembic commands ###
